{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.1576.0 (24.12)+cf7e324bca3ba1dbdfd6f0ddf9a53321538e996d"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Inpatient\",\"Sample File\",\"Parameter1\",\"Transform Sample File\",\"Transform File\",\"Outpatient\",\"Mapping_Specialty\",\"Sample File (2)\",\"Parameter2\",\"Transform Sample File (2)\",\"Transform File (2)\",\"Measures_Table\",\"Calculation Method\",\"All_Data\",\"filepath\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"C:\\Users\\synch\\Dropbox\\pro\\projects\\portfolio\\medokanja\\powerbi\\data\\Inpatient\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "eb58dc94-b2bb-450e-a4c0-85461bbfe309",
        "queryGroup": "Transform File from Inpatient\\Helper Queries"
      },
      {
        "name": "Parameter1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "66b51715-4fd1-47dc-84d2-f6ce95775895",
        "queryGroup": "Transform File from Inpatient\\Helper Queries"
      },
      {
        "name": "Transform Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "938dada3-5ce2-4dfe-a787-c53577f6a4f1",
        "queryGroup": "Transform File from Inpatient"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1 as binary) => let",
          "    Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "0229ff5e-c752-4cd8-bf77-2b63e2d2afd8",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File\"\"}\" ]",
        "queryGroup": "Transform File from Inpatient\\Helper Queries"
      },
      {
        "name": "Sample File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"C:\\Users\\synch\\Dropbox\\pro\\projects\\portfolio\\medokanja\\powerbi\\data\\Outpatient\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "1f928ae6-f916-4ef1-9884-4b43fbfb087a",
        "queryGroup": "Transform File from Outpatient\\Helper Queries"
      },
      {
        "name": "Parameter2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (2)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (2)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "68057404-c8d5-4aba-bf67-08e79a0e404e",
        "queryGroup": "Transform File from Outpatient\\Helper Queries"
      },
      {
        "name": "Transform Sample File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(Parameter2,[Delimiter=\",\", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "4f9ac882-8d29-4c1a-80dc-1b51949705b4",
        "queryGroup": "Transform File from Outpatient"
      },
      {
        "name": "Transform File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter2 as binary) => let",
          "    Source = Csv.Document(Parameter2,[Delimiter=\",\", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "8c85fc89-91a0-482e-8f24-17622cda05c2",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File (2)\"\"}\" ]",
        "queryGroup": "Transform File from Outpatient\\Helper Queries"
      }
    ],
    "extendedProperties": [
      {
        "name": "SQLBI_BRAVO_ManageDatesConfiguration",
        "type": "json",
        "value": {
          "name": "Config-01",
          "autoNaming": 1,
          "autoScan": 127,
          "dateAvailable": true,
          "dateEnabled": true,
          "dateReferenceTableName": "DateAutoTemplate",
          "dateReferenceTableValidation": 1,
          "dateTableName": "Date",
          "dateTableValidation": 1,
          "defaults": {
            "firstDayOfWeek": 0
          },
          "description": "Standard gregorian calendar",
          "exceptTablesColumns": [],
          "holidaysAvailable": true,
          "holidaysDefinitionTableName": "HolidaysDefinition",
          "holidaysDefinitionTableValidation": 0,
          "holidaysEnabled": false,
          "holidaysTableName": "Holidays",
          "holidaysTableValidation": 0,
          "isCurrent": false,
          "isCustom": false,
          "isoCountry": "US",
          "onlyTablesColumns": [],
          "targetMeasures": [],
          "templateUri": "file:///C:/Users/synch/AppData/Local/Bravo/.temp/ManageDates/Templates/Config-01.template.json",
          "timeIntelligenceAvailable": true,
          "timeIntelligenceEnabled": true
        }
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Inpatient"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Inpatient\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Transform File from Outpatient"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Outpatient\\Helper Queries"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_5b572636-5039-41e6-98dc-e3f6f4f321ae",
        "fromColumn": "Specialty",
        "fromTable": "All_Data",
        "toColumn": "Specialty",
        "toTable": "Mapping_Specialty"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Inpatient",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "59ec9fc9-07d3-4aa2-a1a8-bd2a87fc6898",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Archive_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "41047116-4dd5-4104-bfca-219d24ac780a",
            "sourceColumn": "Archive_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Specialty_HIPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0b6a644f-fd57-4a68-9beb-fa7f4615cd0c",
            "sourceColumn": "Specialty_HIPE",
            "summarizeBy": "sum"
          },
          {
            "name": "Specialty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9d3b5336-8842-432c-af93-b51c35c316e9",
            "sourceColumn": "Specialty",
            "summarizeBy": "none"
          },
          {
            "name": "Case_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d95c81d5-a9ed-4429-9307-42939dd1f076",
            "sourceColumn": "Case_Type",
            "summarizeBy": "none"
          },
          {
            "name": "Adult_Child",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fae89293-edfb-461f-adef-eef0b473eb52",
            "sourceColumn": "Adult_Child",
            "summarizeBy": "none"
          },
          {
            "name": "Age_Profile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "594dcbe1-997d-4a12-8c04-8fd76e47c3a9",
            "sourceColumn": "Age_Profile",
            "summarizeBy": "none"
          },
          {
            "name": "Time_Bands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b15d1c82-753d-41f0-b18a-598288ccccbc",
            "sourceColumn": "Time_Bands",
            "summarizeBy": "none"
          },
          {
            "name": "Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "73525fcb-5ca9-47c6-9b91-258a2cdaf729",
            "sourceColumn": "Total",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "bddc4d7c-35c3-4a84-ad96-d1d115de99ec",
        "partitions": [
          {
            "name": "Inpatient",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(filepath&\"medokanja\\powerbi\\data\\Inpatient\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File\", each #\"Transform File\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"Archive_Date\", type text}, {\"Specialty_HIPE\", Int64.Type}, {\"Specialty_Name\", type text}, {\"Case_Type\", type text}, {\"Adult_Child\", type text}, {\"Age_Profile\", type text}, {\"Time_Bands\", type text}, {\"Total\", Int64.Type}, {\"\", type any}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Specialty_Name\", \"Specialty\"}}),",
                "    #\"Changed Type with Locale\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Archive_Date\", type date}}, \"fr-FR\"),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type with Locale\",{\"\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Outpatient",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9a07a88d-920c-40da-87fa-3720413b69db",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Archive_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "237368ca-b476-4de7-b67e-436096418f85",
            "sourceColumn": "Archive_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Specialty_HIPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "04fc6a07-a495-4636-83dd-aff328b76eb5",
            "sourceColumn": "Specialty_HIPE",
            "summarizeBy": "sum"
          },
          {
            "name": "Specialty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2b7ebeae-d67c-4d49-90e7-7bb136382fff",
            "sourceColumn": "Specialty",
            "summarizeBy": "none"
          },
          {
            "name": "Adult_Child",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ef75c646-f8ee-4f8e-982e-30e02df9b9b3",
            "sourceColumn": "Adult_Child",
            "summarizeBy": "none"
          },
          {
            "name": "Age_Profile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ac8901c7-c764-4321-82e1-d4c6449075d0",
            "sourceColumn": "Age_Profile",
            "summarizeBy": "none"
          },
          {
            "name": "Time_Bands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8427a7ef-8ac2-4f94-8a64-3db4182b0ed9",
            "sourceColumn": "Time_Bands",
            "summarizeBy": "none"
          },
          {
            "name": "Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a83ea1ab-d778-4049-bc3d-dd2ab0d20462",
            "sourceColumn": "Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Case_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b681af3-bd2e-4ae7-87c8-dcdb3ad15d14",
            "sourceColumn": "Case_Type",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "934825ef-36db-4249-b8ec-7031fe0700fa",
        "partitions": [
          {
            "name": "Outpatient",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(filepath&\"medokanja\\powerbi\\data\\Outpatient\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File (2)\", each #\"Transform File (2)\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File (2)\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (2)\", Table.ColumnNames(#\"Transform File (2)\"(#\"Sample File (2)\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"Archive_Date\", type text}, {\"Specialty_HIPE\", Int64.Type}, {\"Speciality\", type text}, {\"Adult_Child\", type text}, {\"Age_Profile\", type text}, {\"Time_Bands\", type text}, {\"Total\", Int64.Type}}),",
                "    #\"Changed Type with Locale\" = Table.TransformColumnTypes(#\"Changed Type\", {{\"Archive_Date\", type date}}, \"fr-FR\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type with Locale\",{{\"Speciality\", \"Specialty\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"Case_Type\", each \"Outpatient\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Custom\",{\"Source.Name\", \"Archive_Date\", \"Specialty_HIPE\", \"Specialty\", \"Case_Type\", \"Adult_Child\", \"Age_Profile\", \"Time_Bands\", \"Total\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measures_Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "44caa34d-253b-4745-b2f4-f71e5fec61ff",
        "measures": [
          {
            "name": "LatestMonthWL",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(All_Data[Total]),",
              "    All_Data[Archive_Date] = MAX(All_Data[Archive_Date])",
              ") + 0"
            ],
            "formatString": "0",
            "lineageTag": "1d29ef57-45c9-413d-9e7a-e5eeacd5873e"
          },
          {
            "name": "PYSameMonthWL",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(All_Data[Total]),",
              "    All_Data[Archive_Date] = EDATE(MAX(All_Data[Archive_Date]), -12)",
              ") + 0"
            ],
            "formatString": "0",
            "lineageTag": "9fd2b553-0fab-42d7-9d4b-e9efcd5eb660"
          },
          {
            "name": "AverageWL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(All_Data[Total])",
            "lineageTag": "33453d74-cf3d-4530-8368-3d76074dda42"
          },
          {
            "name": "MedianWL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MEDIAN(All_Data[Total])",
            "lineageTag": "6be7b7f5-417b-4e9b-a273-e7ea9fb654ee"
          },
          {
            "name": "Avg/Med Waitlist",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "SWITCH(",
              "    VALUES('Calculation Method'[Calc Method]), \"Average\", [AverageWL], \"Median\", [MedianWL]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "9ba81574-a207-418b-98d6-d3ef998aa639"
          },
          {
            "name": "YTD LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [LatestMonthWL],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a88b9daf-2119-443c-9c02-5ae8ef8db7a5"
          },
          {
            "name": "QTD LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [LatestMonthWL],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c3a78c80-67b7-4164-ad90-3eed62471335"
          },
          {
            "name": "MTD LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [LatestMonthWL],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f1853257-44be-44c7-ad3e-43f346b242cc"
          },
          {
            "name": "PY LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [LatestMonthWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "97d28327-5290-445c-bd7f-644f600ad84a"
          },
          {
            "name": "YOY LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\LatestMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [LatestMonthWL]",
              "VAR __ValuePreviousPeriod = [PY LatestMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "7eaf1469-1ca0-443f-ad66-b5c52a6e818e"
          },
          {
            "name": "YOY % LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\LatestMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY LatestMonthWL],",
              "    [PY LatestMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "73a27cb3-c4e4-458b-8576-c73094362a12"
          },
          {
            "name": "PQ LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [LatestMonthWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "adc9d020-2b76-4d4f-804c-f6dfd5d3494a"
          },
          {
            "name": "QOQ LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\LatestMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [LatestMonthWL]",
              "VAR __ValuePreviousPeriod = [PQ LatestMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "ec2d02af-cc18-4dde-aba3-a33c5b0792bd"
          },
          {
            "name": "QOQ % LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\LatestMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ LatestMonthWL],",
              "    [PQ LatestMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "636ed971-14c7-48e0-9185-36615922332c"
          },
          {
            "name": "PM LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [LatestMonthWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "18b6bc53-077b-46e8-93b3-7a63421f5c48"
          },
          {
            "name": "MOM LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\LatestMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [LatestMonthWL]",
              "VAR __ValuePreviousPeriod = [PM LatestMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "0652f79e-9813-40d4-a7bf-ed13b3d80ecd"
          },
          {
            "name": "MOM % LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\LatestMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM LatestMonthWL],",
              "    [PM LatestMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "5c554e52-0bf4-4224-b7be-2459bd81652a"
          },
          {
            "name": "PYTD LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD LatestMonthWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "87f686a3-0d48-4038-a78b-abbc3568732e"
          },
          {
            "name": "YOYTD LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\LatestMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD LatestMonthWL]",
              "VAR __ValuePreviousPeriod = [PYTD LatestMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "27e1fcbf-5f4c-4c64-879b-d67e4b4ee4c0"
          },
          {
            "name": "YOYTD % LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\LatestMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD LatestMonthWL],",
              "    [PYTD LatestMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "65421423-be3f-4233-b68a-ababd65073e2"
          },
          {
            "name": "PQTD LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD LatestMonthWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "720fea1f-ac85-4a12-a4aa-3088c76b942b"
          },
          {
            "name": "QOQTD LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\LatestMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD LatestMonthWL]",
              "VAR __ValuePreviousPeriod = [PQTD LatestMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "1d5beab5-af34-4072-b1df-07695469494f"
          },
          {
            "name": "QOQTD % LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\LatestMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD LatestMonthWL],",
              "    [PQTD LatestMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "f88cad46-626a-479b-88c9-fcd23d8960db"
          },
          {
            "name": "PMTD LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD LatestMonthWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7a79e727-185f-4186-9968-97600a315321"
          },
          {
            "name": "MOMTD LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\LatestMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD LatestMonthWL]",
              "VAR __ValuePreviousPeriod = [PMTD LatestMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "c8bb4ed9-9cd5-46b1-8f6e-0d4d27a8678f"
          },
          {
            "name": "MOMTD % LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\LatestMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD LatestMonthWL],",
              "    [PMTD LatestMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "796272f6-1baf-4f1e-91b8-0d6948fbdad0"
          },
          {
            "name": "PYC LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [LatestMonthWL],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f84a44d3-7920-43aa-bc5d-21b0d172a5aa"
          },
          {
            "name": "YTDOPY LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\LatestMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD LatestMonthWL]",
              "VAR __ValuePreviousPeriod = [PYC LatestMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "4c9667b3-2332-4e96-a13f-b8dfb266d175"
          },
          {
            "name": "YDTOPY % LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\LatestMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY LatestMonthWL],",
              "    [PYC LatestMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "edb3e6bb-0dd3-4110-bee4-9178b4dcc2f6"
          },
          {
            "name": "PQC LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [LatestMonthWL],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5c583961-b09b-48a5-94bb-a6388693a0b3"
          },
          {
            "name": "QTDOPQ LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\LatestMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD LatestMonthWL]",
              "VAR __ValuePreviousPeriod = [PQC LatestMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "46aea6da-b88d-4331-91ce-1708e7f9fb90"
          },
          {
            "name": "QDTOPQ % LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\LatestMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ LatestMonthWL],",
              "    [PQC LatestMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "546b2512-94f3-4cb6-93f7-f365759abf79"
          },
          {
            "name": "PMC LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [LatestMonthWL],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6361e26f-f701-4ae5-b428-3434acec5329"
          },
          {
            "name": "MTDOPM LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\LatestMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD LatestMonthWL]",
              "VAR __ValuePreviousPeriod = [PMC LatestMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "8456c6a1-cd65-4b49-8129-5aea5ca15009"
          },
          {
            "name": "MTDOPM % LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\LatestMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM LatestMonthWL],",
              "    [PMC LatestMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "a9622eac-a9d5-4217-af6c-e4c7f35a4e61"
          },
          {
            "name": "MAT LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [LatestMonthWL],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7f5664c9-c32d-47ca-9b21-00f9ffedbed7"
          },
          {
            "name": "PYMAT LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\LatestMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT LatestMonthWL],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "05bfb916-22b7-4fa2-9810-e8e8e1b57c5f"
          },
          {
            "name": "MATG LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\LatestMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT LatestMonthWL]",
              "VAR __ValuePreviousPeriod = [PYMAT LatestMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "6c7d9d46-e6f3-4d60-9be7-d37ac4a7620f"
          },
          {
            "name": "MATG % LatestMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\LatestMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG LatestMonthWL],",
              "    [PYMAT LatestMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "6f1996d8-7757-4b43-ba5e-96951a8b33d8"
          },
          {
            "name": "YTD PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [PYSameMonthWL],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "2681c0c8-72e7-4e2e-b2de-ec798015fe62"
          },
          {
            "name": "QTD PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [PYSameMonthWL],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "9697563d-50b0-45f8-a83f-1adb50dc0286"
          },
          {
            "name": "MTD PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [PYSameMonthWL],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3278a40e-7ee8-4ed3-8076-75236e513ec5"
          },
          {
            "name": "PY PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [PYSameMonthWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6b13926b-6f50-42a4-987b-e2aefedf5421"
          },
          {
            "name": "YOY PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\PYSameMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [PYSameMonthWL]",
              "VAR __ValuePreviousPeriod = [PY PYSameMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "44745ac0-d22f-44bc-8a40-0dce65f4355d"
          },
          {
            "name": "YOY % PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\PYSameMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY PYSameMonthWL],",
              "    [PY PYSameMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "aba7c663-b1ae-45c6-83b9-483276be1b9b"
          },
          {
            "name": "PQ PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [PYSameMonthWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3668d291-0bc5-45c4-ba3d-6128f932f235"
          },
          {
            "name": "QOQ PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\PYSameMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [PYSameMonthWL]",
              "VAR __ValuePreviousPeriod = [PQ PYSameMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "14aee0f6-a024-45ac-b085-0079dd726800"
          },
          {
            "name": "QOQ % PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\PYSameMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ PYSameMonthWL],",
              "    [PQ PYSameMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "2345c8cb-a010-49c9-a147-cbc3aaaa7da0"
          },
          {
            "name": "PM PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [PYSameMonthWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "0a4ce5b1-6a22-4f60-ada3-efa9fcaaf155"
          },
          {
            "name": "MOM PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\PYSameMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [PYSameMonthWL]",
              "VAR __ValuePreviousPeriod = [PM PYSameMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "b46caf12-2ca4-458d-a23e-edd0cc54a3f1"
          },
          {
            "name": "MOM % PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\PYSameMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM PYSameMonthWL],",
              "    [PM PYSameMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "73f25c1f-bcb7-4267-8914-de7396909df0"
          },
          {
            "name": "PYTD PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD PYSameMonthWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "588465b3-75f5-4836-8487-7f8e7ed161c4"
          },
          {
            "name": "YOYTD PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\PYSameMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD PYSameMonthWL]",
              "VAR __ValuePreviousPeriod = [PYTD PYSameMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "f74b7a69-0188-4a46-9e43-4d399476d3d6"
          },
          {
            "name": "YOYTD % PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\PYSameMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD PYSameMonthWL],",
              "    [PYTD PYSameMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "f8278a79-b637-4ad0-a02a-0d74ac81cc78"
          },
          {
            "name": "PQTD PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD PYSameMonthWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "610757e0-d0c2-4003-a4ab-5608e5b4d933"
          },
          {
            "name": "QOQTD PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\PYSameMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD PYSameMonthWL]",
              "VAR __ValuePreviousPeriod = [PQTD PYSameMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "fcf69584-8561-4d06-b8e3-f810983b9f71"
          },
          {
            "name": "QOQTD % PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\PYSameMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD PYSameMonthWL],",
              "    [PQTD PYSameMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "2e3f3468-e5e1-490d-9767-c1b00a313bc9"
          },
          {
            "name": "PMTD PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD PYSameMonthWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7f7433fc-54d9-4873-9baa-da2a2caed276"
          },
          {
            "name": "MOMTD PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\PYSameMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD PYSameMonthWL]",
              "VAR __ValuePreviousPeriod = [PMTD PYSameMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "7ac34742-515d-4edc-ab02-9248d6ca0e94"
          },
          {
            "name": "MOMTD % PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\PYSameMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD PYSameMonthWL],",
              "    [PMTD PYSameMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "45307c6f-e3c2-4501-8e21-691b81fcb5f0"
          },
          {
            "name": "PYC PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [PYSameMonthWL],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4245110d-9ab6-48ac-9fa7-c1d4b0193746"
          },
          {
            "name": "YTDOPY PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\PYSameMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD PYSameMonthWL]",
              "VAR __ValuePreviousPeriod = [PYC PYSameMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "1cceaba7-02df-4da0-bd38-4ed4c8e22c1d"
          },
          {
            "name": "YDTOPY % PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\PYSameMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY PYSameMonthWL],",
              "    [PYC PYSameMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "d15551d0-fd00-443b-ae30-8998a59a9ccb"
          },
          {
            "name": "PQC PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [PYSameMonthWL],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a6c52124-aa93-461b-a485-9509f3177fcc"
          },
          {
            "name": "QTDOPQ PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\PYSameMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD PYSameMonthWL]",
              "VAR __ValuePreviousPeriod = [PQC PYSameMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "157be53b-8fb0-4c8c-a8ba-4e3898b9a1d4"
          },
          {
            "name": "QDTOPQ % PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\PYSameMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ PYSameMonthWL],",
              "    [PQC PYSameMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "c3100271-2cf6-420f-9502-7c09bcc4653f"
          },
          {
            "name": "PMC PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [PYSameMonthWL],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c0ee4998-bed5-49a3-b3b4-2edfa7cf4ca2"
          },
          {
            "name": "MTDOPM PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\PYSameMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD PYSameMonthWL]",
              "VAR __ValuePreviousPeriod = [PMC PYSameMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "1f7336e4-07d5-4557-9e90-8554407ae873"
          },
          {
            "name": "MTDOPM % PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\PYSameMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM PYSameMonthWL],",
              "    [PMC PYSameMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "ce013e01-0086-434a-8e6b-165386c6f312"
          },
          {
            "name": "MAT PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [PYSameMonthWL],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6b4f2993-7764-4e5b-9faf-028dd0ff4c37"
          },
          {
            "name": "PYMAT PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\PYSameMonthWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT PYSameMonthWL],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4773623b-f8cb-4ece-83fc-09621205859a"
          },
          {
            "name": "MATG PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\PYSameMonthWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT PYSameMonthWL]",
              "VAR __ValuePreviousPeriod = [PYMAT PYSameMonthWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "lineageTag": "a223bac5-8185-4fb5-93e2-14be66249358"
          },
          {
            "name": "MATG % PYSameMonthWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\PYSameMonthWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG PYSameMonthWL],",
              "    [PYMAT PYSameMonthWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "c81a88b3-62e0-4b0e-81f3-ec37c1b36b4d"
          },
          {
            "name": "YTD AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [AverageWL],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "3b8c9db9-9a18-4160-9e41-a2977bac392a"
          },
          {
            "name": "QTD AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [AverageWL],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "45255c98-c079-4409-984b-ea8a9ac005b6"
          },
          {
            "name": "MTD AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [AverageWL],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "6d088f85-28d4-44d2-b8e4-47d2aa26cde0"
          },
          {
            "name": "PY AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [AverageWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "857f6a8d-6cf4-480d-9117-65b0febc5ca1"
          },
          {
            "name": "YOY AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\AverageWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [AverageWL]",
              "VAR __ValuePreviousPeriod = [PY AverageWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "aea8996d-2824-4e97-bb7c-e465a7263ab9"
          },
          {
            "name": "YOY % AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\AverageWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY AverageWL],",
              "    [PY AverageWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "16210ea1-d22f-4ab4-867c-63279c7e9f47"
          },
          {
            "name": "PQ AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [AverageWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "d981f2cd-ad1c-4b33-8083-1c2dc0ea8c3c"
          },
          {
            "name": "QOQ AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\AverageWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [AverageWL]",
              "VAR __ValuePreviousPeriod = [PQ AverageWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "cae63ae8-8a5c-4abd-ac70-8004f95f73c7"
          },
          {
            "name": "QOQ % AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\AverageWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ AverageWL],",
              "    [PQ AverageWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "9d97bb23-9fd8-4b88-9ff7-4af888667195"
          },
          {
            "name": "PM AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [AverageWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "8d2114d5-7dcd-4ac9-91af-a997705a585d"
          },
          {
            "name": "MOM AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\AverageWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [AverageWL]",
              "VAR __ValuePreviousPeriod = [PM AverageWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "6f4de336-a93f-43cc-b761-b311f032229e"
          },
          {
            "name": "MOM % AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\AverageWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM AverageWL],",
              "    [PM AverageWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "cf79c72c-bb23-42b9-85aa-de17bb0e2c81"
          },
          {
            "name": "PYTD AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD AverageWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "995f02a9-f375-4bef-b8f0-b168370c1c08"
          },
          {
            "name": "YOYTD AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\AverageWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD AverageWL]",
              "VAR __ValuePreviousPeriod = [PYTD AverageWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "212ce46c-87f5-4265-b3e4-6a4cbb7eb7f3"
          },
          {
            "name": "YOYTD % AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\AverageWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD AverageWL],",
              "    [PYTD AverageWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "9cc336eb-f29c-4654-bcc4-07acea38e529"
          },
          {
            "name": "PQTD AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD AverageWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "ceb2d52b-9bf3-4bfc-afa2-65fa928f1a22"
          },
          {
            "name": "QOQTD AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\AverageWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD AverageWL]",
              "VAR __ValuePreviousPeriod = [PQTD AverageWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "6dd1f268-a041-4386-9714-281721a62347"
          },
          {
            "name": "QOQTD % AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\AverageWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD AverageWL],",
              "    [PQTD AverageWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "43e69a4e-e374-4fe2-bbf2-95352ed873de"
          },
          {
            "name": "PMTD AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD AverageWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "9c544e2a-68a0-433b-8ff1-a059d52d98b1"
          },
          {
            "name": "MOMTD AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\AverageWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD AverageWL]",
              "VAR __ValuePreviousPeriod = [PMTD AverageWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "30c438d4-0f10-4345-af50-e5f60233bb1c"
          },
          {
            "name": "MOMTD % AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\AverageWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD AverageWL],",
              "    [PMTD AverageWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "32ab4f7d-e079-48f3-b20b-7a049cee9879"
          },
          {
            "name": "PYC AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [AverageWL],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "lineageTag": "eb7e8959-80fc-4e87-8931-966479a86f4d"
          },
          {
            "name": "YTDOPY AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\AverageWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD AverageWL]",
              "VAR __ValuePreviousPeriod = [PYC AverageWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "35d82568-71d7-4b11-95d5-f68673ebd70d"
          },
          {
            "name": "YDTOPY % AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\AverageWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY AverageWL],",
              "    [PYC AverageWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "5c36cfe2-615a-4ee5-a708-22da482d9422"
          },
          {
            "name": "PQC AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [AverageWL],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "lineageTag": "50b3115b-b311-454a-a827-9c969fec0f64"
          },
          {
            "name": "QTDOPQ AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\AverageWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD AverageWL]",
              "VAR __ValuePreviousPeriod = [PQC AverageWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "e6e77f98-1494-4669-ad0c-aa6e2d88c25d"
          },
          {
            "name": "QDTOPQ % AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\AverageWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ AverageWL],",
              "    [PQC AverageWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "f570c3fc-5b80-41e0-9daf-07406a63a12b"
          },
          {
            "name": "PMC AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [AverageWL],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "lineageTag": "13c40754-49a8-430d-9fab-01db6301e49e"
          },
          {
            "name": "MTDOPM AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\AverageWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD AverageWL]",
              "VAR __ValuePreviousPeriod = [PMC AverageWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "13e9ca82-2ad0-4b8e-8af1-df6d62601614"
          },
          {
            "name": "MTDOPM % AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\AverageWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM AverageWL],",
              "    [PMC AverageWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "b5c4494f-7bb3-48eb-9570-d09268e08085"
          },
          {
            "name": "MAT AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [AverageWL],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "5b90ad77-8604-43c4-a2b7-2d828355e0f2"
          },
          {
            "name": "PYMAT AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\AverageWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT AverageWL],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "lineageTag": "70f624ac-5f9c-4982-ab76-58b3cbd6461f"
          },
          {
            "name": "MATG AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\AverageWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT AverageWL]",
              "VAR __ValuePreviousPeriod = [PYMAT AverageWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "40aaf380-99fc-4846-8e42-61d7cef213ab"
          },
          {
            "name": "MATG % AverageWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\AverageWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG AverageWL],",
              "    [PYMAT AverageWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "d5f10d03-df63-42f7-bec9-50bda412a998"
          },
          {
            "name": "YTD MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MedianWL],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "4d63a35d-976b-4026-b166-f1df51a7a4e1"
          },
          {
            "name": "QTD MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MedianWL],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "ee6749d0-69bc-430c-ae58-bdf707731f98"
          },
          {
            "name": "MTD MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MedianWL],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "1fa77f41-97e0-46cb-b70c-c108911a22ca"
          },
          {
            "name": "PY MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MedianWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "72d285d0-abd8-4968-a11c-70c9b048b699"
          },
          {
            "name": "YOY MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\MedianWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MedianWL]",
              "VAR __ValuePreviousPeriod = [PY MedianWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "3508d8f8-2223-4f8d-a23b-c40aa8d53a37"
          },
          {
            "name": "YOY % MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\MedianWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY MedianWL],",
              "    [PY MedianWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "451a8574-21bd-4a15-8ac2-a4923e451bab"
          },
          {
            "name": "PQ MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MedianWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "02f4a92a-7bec-452d-8d39-a53e8b955174"
          },
          {
            "name": "QOQ MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\MedianWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MedianWL]",
              "VAR __ValuePreviousPeriod = [PQ MedianWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "b98fd81b-0d7f-47f4-aef3-c4d12a4131ba"
          },
          {
            "name": "QOQ % MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\MedianWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ MedianWL],",
              "    [PQ MedianWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "99bd6412-04e7-4ecf-9072-ea036f3af6d5"
          },
          {
            "name": "PM MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MedianWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "f542c949-aa59-43ca-9dc8-3f75aad03c56"
          },
          {
            "name": "MOM MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\MedianWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MedianWL]",
              "VAR __ValuePreviousPeriod = [PM MedianWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "4d8d3bc8-2c58-4de2-b677-3b5d79a7757a"
          },
          {
            "name": "MOM % MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\MedianWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM MedianWL],",
              "    [PM MedianWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "a4920934-0a3d-4727-9065-1b32396f3d91"
          },
          {
            "name": "PYTD MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD MedianWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "b2d28810-edcb-4a43-acce-0902041ef1bd"
          },
          {
            "name": "YOYTD MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\MedianWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD MedianWL]",
              "VAR __ValuePreviousPeriod = [PYTD MedianWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "d5c2ada8-3d25-4dca-8993-62dbeb02f66f"
          },
          {
            "name": "YOYTD % MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\MedianWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD MedianWL],",
              "    [PYTD MedianWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "b02ae1f5-57ec-4bcc-a860-36733a321bf7"
          },
          {
            "name": "PQTD MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD MedianWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "bbf55e68-c7ee-4598-8b1a-d503a031ca39"
          },
          {
            "name": "QOQTD MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\MedianWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD MedianWL]",
              "VAR __ValuePreviousPeriod = [PQTD MedianWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "57330528-ce27-4f7b-bea1-cd58e816a6ec"
          },
          {
            "name": "QOQTD % MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\MedianWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD MedianWL],",
              "    [PQTD MedianWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "1d6c2a65-d7b3-4532-aeef-d10874dcb1f6"
          },
          {
            "name": "PMTD MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD MedianWL],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "a3ed4a60-8afe-45d3-ba18-4f3d6b1d8677"
          },
          {
            "name": "MOMTD MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\MedianWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD MedianWL]",
              "VAR __ValuePreviousPeriod = [PMTD MedianWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "f98ed5d2-eef5-459f-a597-f3577aff333f"
          },
          {
            "name": "MOMTD % MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\MedianWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD MedianWL],",
              "    [PMTD MedianWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "c0aae5a3-4843-463c-806a-c78133e1ca52"
          },
          {
            "name": "PYC MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MedianWL],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "lineageTag": "e399083f-df89-495c-bb45-57b32e06e581"
          },
          {
            "name": "YTDOPY MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\MedianWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD MedianWL]",
              "VAR __ValuePreviousPeriod = [PYC MedianWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "327f568b-e213-44d8-8f09-8679a435f730"
          },
          {
            "name": "YDTOPY % MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\MedianWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY MedianWL],",
              "    [PYC MedianWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "2160d7e2-c1b3-4240-9ad8-80b49e3d9f1a"
          },
          {
            "name": "PQC MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MedianWL],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "lineageTag": "2da749a4-edde-4a61-a626-105597252453"
          },
          {
            "name": "QTDOPQ MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\MedianWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD MedianWL]",
              "VAR __ValuePreviousPeriod = [PQC MedianWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "4acd4817-0a19-4c6d-b0dd-3bfcfae55250"
          },
          {
            "name": "QDTOPQ % MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\MedianWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ MedianWL],",
              "    [PQC MedianWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "1dd5e552-a2b0-4ff1-a662-dc411e0fa7a8"
          },
          {
            "name": "PMC MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MedianWL],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "lineageTag": "10a11832-e265-4397-be49-73fb7e9441a5"
          },
          {
            "name": "MTDOPM MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\MedianWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD MedianWL]",
              "VAR __ValuePreviousPeriod = [PMC MedianWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "6eee0867-fc3b-49b8-b901-c9c1e0d10dcb"
          },
          {
            "name": "MTDOPM % MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\MedianWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM MedianWL],",
              "    [PMC MedianWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "37a51c0c-ae38-4666-9f56-d103df3337cc"
          },
          {
            "name": "MAT MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MedianWL],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "fffa7a04-aa14-4efb-a46d-f9309f793cdb"
          },
          {
            "name": "PYMAT MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\MedianWL",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT MedianWL],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "lineageTag": "5653d026-857d-46d5-94a5-6784667aa880"
          },
          {
            "name": "MATG MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\MedianWL",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT MedianWL]",
              "VAR __ValuePreviousPeriod = [PYMAT MedianWL]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "da613ebd-f242-4fab-a665-16b157c0ce61"
          },
          {
            "name": "MATG % MedianWL",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\MedianWL",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG MedianWL],",
              "    [PYMAT MedianWL]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "d6363aa5-7c21-4081-8a74-f79e4e555085"
          },
          {
            "name": "YTD Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Avg/Median Wait List],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "9d7e9b74-28e4-40d9-9dcf-a9a87066169e"
          },
          {
            "name": "QTD Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Avg/Median Wait List],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "cec9d92b-d945-4ef2-a334-2e4e2199d6f2"
          },
          {
            "name": "MTD Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date total\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Avg/Median Wait List],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "lineageTag": "7e384bb4-a282-40a3-9b41-2dbebc5789c0"
          },
          {
            "name": "PY Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Avg/Median Wait List],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "f4c854fe-addc-4a41-b9ce-8101dc80fe50"
          },
          {
            "name": "YOY Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Avg/Median Wait List",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Avg/Med Waitlist]",
              "VAR __ValuePreviousPeriod = [PY Avg/Median Wait List]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "3e5bb874-d7c6-473e-a416-ea2b3e546c44"
          },
          {
            "name": "YOY % Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Avg/Median Wait List",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY Avg/Median Wait List],",
              "    [PY Avg/Median Wait List]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "aa5703ce-64dd-405a-80fc-02de293e219a"
          },
          {
            "name": "PQ Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Avg/Median Wait List],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "070a8e16-e73f-4b6d-8086-180d3b70b162"
          },
          {
            "name": "QOQ Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Avg/Median Wait List",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Avg/Med Waitlist]",
              "VAR __ValuePreviousPeriod = [PQ Avg/Median Wait List]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "36ed3b69-9acb-49a0-84a9-d245abda679a"
          },
          {
            "name": "QOQ % Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Avg/Median Wait List",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ Avg/Median Wait List],",
              "    [PQ Avg/Median Wait List]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "ca81446b-df68-43b8-b7dd-6175237f4454"
          },
          {
            "name": "PM Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Avg/Median Wait List],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "4141f6f2-235d-483f-953a-057b56f5445e"
          },
          {
            "name": "MOM Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Avg/Median Wait List",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Avg/Med Waitlist]",
              "VAR __ValuePreviousPeriod = [PM Avg/Median Wait List]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "3828cd30-cd69-404a-bbc9-46f0be050c8a"
          },
          {
            "name": "MOM % Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth\\Avg/Median Wait List",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM Avg/Median Wait List],",
              "    [PM Avg/Median Wait List]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "d308e7c1-3796-4960-b673-160f8030f91e"
          },
          {
            "name": "PYTD Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD Avg/Median Wait List],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "a9a924c6-c4ac-408e-892e-5421c8e3aacd"
          },
          {
            "name": "YOYTD Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Avg/Median Wait List",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Avg/Median Wait List]",
              "VAR __ValuePreviousPeriod = [PYTD Avg/Median Wait List]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "6d76f4a8-78d2-443c-a0a0-c55bf4849b57"
          },
          {
            "name": "YOYTD % Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Avg/Median Wait List",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD Avg/Median Wait List],",
              "    [PYTD Avg/Median Wait List]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "31f2e7b0-b94a-4535-af4a-039f4d5ba6ab"
          },
          {
            "name": "PQTD Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD Avg/Median Wait List],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "a5b01396-74aa-4059-9a14-d2e36f089a86"
          },
          {
            "name": "QOQTD Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Avg/Median Wait List",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Avg/Median Wait List]",
              "VAR __ValuePreviousPeriod = [PQTD Avg/Median Wait List]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "fbed1cf9-56aa-4075-9c12-cd0e0fcc1ed7"
          },
          {
            "name": "QOQTD % Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Avg/Median Wait List",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD Avg/Median Wait List],",
              "    [PQTD Avg/Median Wait List]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "1c3da8ee-4971-4087-90ea-96b70d6491fa"
          },
          {
            "name": "PMTD Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD Avg/Median Wait List],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "ab94348c-70ed-426c-934c-25942d9a9fd2"
          },
          {
            "name": "MOMTD Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Avg/Median Wait List",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Avg/Median Wait List]",
              "VAR __ValuePreviousPeriod = [PMTD Avg/Median Wait List]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "c8bff821-5638-4dc9-8767-2ff367545f60"
          },
          {
            "name": "MOMTD % Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Avg/Median Wait List",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD Avg/Median Wait List],",
              "    [PMTD Avg/Median Wait List]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "f2a07b1c-98cd-4121-b780-b8860b64d0cb"
          },
          {
            "name": "PYC Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Avg/Median Wait List],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "lineageTag": "5618aef8-73d5-4919-9243-a58ad848b9ee"
          },
          {
            "name": "YTDOPY Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Avg/Median Wait List",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Avg/Median Wait List]",
              "VAR __ValuePreviousPeriod = [PYC Avg/Median Wait List]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "18d4dda5-e095-4c45-b5e3-60a7c305fa13"
          },
          {
            "name": "YDTOPY % Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Avg/Median Wait List",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY Avg/Median Wait List],",
              "    [PYC Avg/Median Wait List]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "08017d0f-9a61-4986-b686-f571717a67c5"
          },
          {
            "name": "PQC Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Avg/Median Wait List],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "lineageTag": "d42f019f-5916-4192-b886-882a8caf8db7"
          },
          {
            "name": "QTDOPQ Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Avg/Median Wait List",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Avg/Median Wait List]",
              "VAR __ValuePreviousPeriod = [PQC Avg/Median Wait List]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "87639959-b1aa-4ce3-8f82-77b881abcef9"
          },
          {
            "name": "QDTOPQ % Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Avg/Median Wait List",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ Avg/Median Wait List],",
              "    [PQC Avg/Median Wait List]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "37cda517-0e0b-4afc-9f15-c01f2320bc94"
          },
          {
            "name": "PMC Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Avg/Median Wait List],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "lineageTag": "1fd46399-bf4d-40c0-b90c-f22a2b2d4730"
          },
          {
            "name": "MTDOPM Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Avg/Median Wait List",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Avg/Median Wait List]",
              "VAR __ValuePreviousPeriod = [PMC Avg/Median Wait List]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "3889f86e-84a7-4184-971b-992cf11f2390"
          },
          {
            "name": "MTDOPM % Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Avg/Median Wait List",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM Avg/Median Wait List],",
              "    [PMC Avg/Median Wait List]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "f1e72a1b-fb90-4a34-b605-8ac5b3dababa"
          },
          {
            "name": "MAT Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Avg/Median Wait List],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "4003b114-8974-4605-a53c-1f3b960ac9a5"
          },
          {
            "name": "PYMAT Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Avg/Median Wait List",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT Avg/Median Wait List],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "lineageTag": "d73b5dc2-0786-4094-b5f6-48749c254818"
          },
          {
            "name": "MATG Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Avg/Median Wait List",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT Avg/Median Wait List]",
              "VAR __ValuePreviousPeriod = [PYMAT Avg/Median Wait List]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "lineageTag": "601f0aaa-a905-4b8f-9ac7-5034ac3f2e48"
          },
          {
            "name": "MATG % Avg/Median Wait List",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Avg/Median Wait List",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG Avg/Median Wait List],",
              "    [PYMAT Avg/Median Wait List]",
              ")"
            ],
            "formatString": "0.00%",
            "lineageTag": "dc070903-9b3a-46b2-859d-c6450afa1ebd"
          },
          {
            "name": "Dynamic Title",
            "expression": [
              "",
              "SWITCH(",
              "    VALUES('Calculation Method'[Calc Method]), \"Average\", \"Key Indicators - Patient Wait List (Average)\", \"Median\", \"Key Indicators - Patient Wait List (Median)\"",
              ")"
            ],
            "lineageTag": "c4d1707f-2c82-4281-b2dd-c2d249ec7d88"
          },
          {
            "name": "NoDataLeft",
            "expression": "IF(ISBLANK(CALCULATE(sum(All_Data[Total]),All_Data[Case_Type]<>\"Outpatient\")), \"No data for selected criteria\", \"\")",
            "lineageTag": "cf680206-4204-4e09-9b3f-09b820c36923"
          },
          {
            "name": "NoDataRight",
            "expression": "IF(ISBLANK(CALCULATE(sum(All_Data[Total]),All_Data[Case_Type]=\"Outpatient\")), \"No data for selected criteria\", \"\")",
            "lineageTag": "d80d8680-6bf6-4cad-ad68-907803b70039"
          },
          {
            "name": "sum",
            "expression": "SUM(All_Data[Total])",
            "formatString": "0",
            "lineageTag": "d81d6b0e-8f63-4e5c-b75d-e38b450016af"
          }
        ],
        "partitions": [
          {
            "name": "Measures_Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calculation Method",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Calc Method",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73d547d4-9a05-441a-b6c7-3d833a700ca3",
            "sourceColumn": "Calc Method",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "55d1a58e-98aa-477d-88f9-2e60b91a4c07",
        "partitions": [
          {
            "name": "Calculation Method",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcixLLUpMT1WK1YlW8k1NyUzMU4qNBQA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Calc Method\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Calc Method\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "All_Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26b02ab6-aac9-40aa-9682-a33dd71fa254",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Archive_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "d mmmm\\, yyyy",
            "lineageTag": "7140b5f8-a654-4d0c-8377-07dffbab339d",
            "sourceColumn": "Archive_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Specialty_HIPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "15eed650-8eb6-46e6-8069-ddfe4dc6c2b4",
            "sourceColumn": "Specialty_HIPE",
            "summarizeBy": "sum"
          },
          {
            "name": "Specialty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0067f94b-7cc5-498e-87f4-f6c45058ff9c",
            "sourceColumn": "Specialty",
            "summarizeBy": "none"
          },
          {
            "name": "Case_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36816ce5-fd44-45ff-8988-f3ec809a5a54",
            "sourceColumn": "Case_Type",
            "summarizeBy": "none"
          },
          {
            "name": "Adult_Child",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25a99dfc-feba-437f-9edf-5744b7b81540",
            "sourceColumn": "Adult_Child",
            "summarizeBy": "none"
          },
          {
            "name": "Age_Profile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c77bc85-2e08-44d2-81e5-5f809a888e0f",
            "sourceColumn": "Age_Profile",
            "summarizeBy": "none"
          },
          {
            "name": "Time_Bands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "827d5386-37d2-4b37-a558-fa6821885af8",
            "sourceColumn": "Time_Bands",
            "summarizeBy": "none"
          },
          {
            "name": "Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "b6e9f9cd-066e-4d55-b5f5-5aae30374259",
            "sourceColumn": "Total",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "abf1226b-0162-4445-8595-24c34c3520fa",
        "partitions": [
          {
            "name": "All_Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.Combine({Inpatient, Outpatient}),",
                "    #\"Replaced 18 Months+ (Time)\" = Table.ReplaceValue(Source,\"18 Months +\",\"18+ Months\",Replacer.ReplaceText,{\"Time_Bands\"}),",
                "    #\"Trimmed Age and time\" = Table.TransformColumns(#\"Replaced 18 Months+ (Time)\",{{\"Time_Bands\", Text.Trim, type text}, {\"Age_Profile\", Text.Trim, type text}}),",
                "    #\"for Age+Time replace blank\" = Table.ReplaceValue(#\"Trimmed Age and time\",\"\",\"No Input\",Replacer.ReplaceValue,{\"Age_Profile\", \"Time_Bands\"})",
                "in",
                "    #\"for Age+Time replace blank\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Mapping_Specialty",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Specialty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26bce861-4b5c-4d71-ac10-a28b685b9d18",
            "sourceColumn": "Specialty",
            "summarizeBy": "none"
          },
          {
            "name": "Specialty Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "293c2cd3-088d-4014-ae15-4a4d31f06b84",
            "sourceColumn": "Specialty Group",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "beedde40-0a37-42af-a934-86a6e2323db6",
        "partitions": [
          {
            "name": "Mapping_Specialty",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(filepath&\"medokanja\\powerbi\\data\\Mapping_Specialty.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Specialty\", type text}, {\"Specialty Group\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "filepath",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "filepath",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8c02c725-2989-4808-bccb-2076b2184e8a",
            "sourceColumn": "filepath",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "a689afd1-e58c-4df2-8968-fa14027cb130",
        "partitions": [
          {
            "name": "filepath",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = \"C:\\Users\\synch\\Dropbox\\pro\\projects\\portfolio\\\"",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}
